### PR TITLE
Feature: Add support for meta data

### LINKED ISSUE #1: Add support for meta data
Hey @ebsamson3,

First of all: Thanks a lot for this great repository! Integrating it into my project worked like a charm, and the README is very thorough and pretty to look at. 👍🏼

For a project that I am working on, I need to access the elements' `version`. According to the [Overpass API Language Guide][1], this is achieved by using `out meta;`. I looked at SwiftOverpassAPI's models and parsing, and was unable to find the place where the meta data is parsed and retained.

Therefore, I suggest to add a new `struct` `Meta`:

```swift
public struct Meta {
    public let version: Int
    public let timestamp: String
    public let changeset: Int
    public let userId: Int
    public let username: String
}
```

The existing models would then incorporate it like this:

```swift
public struct OPNode: OPElement {
    /// ...
    public let meta: Meta?
}
```

What do you think? Is this something that could be part of this project?

[1]: https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide

### PR DESCRIPTION
**Pull request by wtimme**
This branch resolves #1 by adding a new struct `OPMeta`.

I've already tested this branch in my own project, and it seems to work fine:

Screenshot 2020-04-06 at 19 09 00

### CODE REVIEW

**Comment by wtimme** [comment]
Hey @ebsamson3, is there anything I can do to further this pull request? Is this change something that you are interested in at all? Thanks in advance for your feedback, and have a great weekend!

**Comment by ebsamson3** [comment]
@wtimme Thanks for your contribution. I really appreciate it. I'm trying to finish off a sprint for my work right now but once it is over I'll review it.

**Comment by wtimme** [comment]
Hey @ebsamson3, how did that sprint go?

I'm using your project in one of mine and since the pull request hasn't been merged yet, [I am using the branch][1] in my Podfile. 😅 Is there something that I can do to further this pull request? Thanks in advance for your time and effort!

[1]: https://github.com/wtimme/OSM-Surveyor/blob/develop/Podfile#L17

**Comment by ebsamson3** [comment]
> Hey @ebsamson3, how did that sprint go?
> 
> I'm using your project in one of mine and since the pull request hasn't been merged yet, [I am using the branch](https://github.com/wtimme/OSM-Surveyor/blob/develop/Podfile#L17) in my Podfile. 😅 Is there something that I can do to further this pull request? Thanks in advance for your time and effort!

Reviewing. It might take me a second to get reacquainted with this project. Sorry for the delay and thank you for your patience.

**Comment by ebsamson3** [comment]
@wtimme 

I think the main thing to add would be some way to utilize the metadata the example project. Maybe in `DemoViewModel.swift` you could add to the print statement on line 99 to also print the metadata if it exists. 

We should also be creating a new release, but I'll have to look into how to the precise details on how to do that tomorrow. My work doesn't use third party libraries so I haven't had a lot of recent experience w/ cocoapods. I think the only thing that needs to be changed is the release in the podspec file but don't quote me on that. If you have any insight on this I'd be happy to have it. 

Other than that it looks good to me. I don't have any comments on the existing code changes.

**Comment by wtimme** [comment]
Thanks for taking a look, @ebsamson3! I've added a `print()` statement to the `DemoViewModel` just like you asked.

It took me some time as well to get familiar again with the branch. In order to verify that my changes were working, I temporarily changed the `OPQueryOutputType`'s `toString()` method so that for the case `.center`, it would return `out meta center;`. That way, the meta data is included when querying Overpass in the example project.

That also made me realize that `.meta` is missing from the `OPQueryOutputType`s. Do you think it makes sense to add it there?

**Comment by ebsamson3** [comment]
@wtimme 

Looking at the [query language docs](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Output_Format_.28out.29) it looks like meta an is output verbosity setting where as things like center are a geological information modifier. So you could technically add both modifiers (`out meta center;` for example). 

If you can live without meta being an OPQueryOutput type for now, I would say hold off on it. I can work on a separate update that allows for specifying the verbosity independently of the geometry setting.

**Comment by wtimme** [comment]
Sounds good. Let's not delay the pull request for this.

**Comment by ebsamson3** [comment]
Ok, you should be able to update your podfile now. Let me know if you have any trouble with the new release.

**Comment by wtimme** [comment]
Everything is working as expected. Thanks for your time and effort, @ebsamson3!

**Pull request merged**
